version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'jamFixRabbitMQ'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 8050:15672
      - 5672:5672
    expose:
      - 5672
    networks: 
    - jamfixnetwork
  # SQL Server Docker Container
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=jamfix123!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - jamfixnetwork

  # ASP.NET Core Application Docker Container
  api:
    restart: unless-stopped
    build:
      context: ./RS2
    environment:
      - ConnectionStrings:DefaultConnection=Server=sql,1433;Database=IB190065;User=sa;Password=jamfix123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7097:7097
    networks:
      - jamfixnetwork
    links:
      - sql
    depends_on:
      - sql

  jamfixauxiliary:
    restart: unless-stopped
    build:
      context: ./JamFixTestAPI2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7108:7108
    networks:
      - jamfixnetwork
    depends_on:
      - rabbitMQ
networks:
  jamfixnetwork:
    driver: bridge